import { readFileSync, writeFileSync } from 'node:fs'

const hostPath = 'src/index.host.js'
let host = readFileSync(hostPath, 'utf8')

const repairMarker = `      async function repairMechanismCoverageHost(task, model, batch, accepted, acc, existingIds, existingDigest, batchContext, totalParagraphs) {\n`
if (!host.includes(repairMarker)) throw new Error('coverage repair marker not found')
const helper = `      function pruneCoverageSemanticStrengthDriftHost(repair, gate) {\n        if (!repair || !Array.isArray(repair.nodes) || !gate || !Array.isArray(gate.blockingIssues)) return []\n        const repairIds = new Set(repair.nodes.map((node) => node && node.id).filter(Boolean))\n        const prunedIds = []\n        const seen = new Set()\n        for (const issue of gate.blockingIssues) {\n          if (!issue || issue.code !== 'node_semantic_strength_drift' || typeof issue.targetId !== 'string') continue\n          if (!repairIds.has(issue.targetId) || seen.has(issue.targetId)) continue\n          seen.add(issue.targetId)\n          prunedIds.push(issue.targetId)\n        }\n        if (prunedIds.length === 0) return []\n        const drop = new Set(prunedIds)\n        repair.nodes = repair.nodes.filter((node) => node && !drop.has(node.id))\n        repair.edges = (Array.isArray(repair.edges) ? repair.edges : []).filter((edge) => edge && !drop.has(edge.fromNodeId) && !drop.has(edge.toNodeId))\n        repair.warnings = Array.isArray(repair.warnings) ? repair.warnings : []\n        for (const id of prunedIds) repair.warnings.push('coverage_pruned:node_semantic_strength_drift:' + id)\n        return prunedIds\n      }\n\n`
host = host.replace(repairMarker, helper + repairMarker)

const gateOld = `          const safe = applySafeInvariantRepairsHost(repair, gate, { allowEdgeDrops: true }).repairs\n          if (safe.length > 0) gate = validateGraphInvariantsHost(repair, task.text, {\n            includeQuality: false,\n            extraNodes: knownNodes,\n            normalizationWarnings: repair.warnings,\n            ignoreSafeNormalizationDrops: true,\n          })\n          if (gate.blockingIssues.length > 0) throw new Error(formatInvariantFeedbackHost(gate.blockingIssues))\n`
const gateNew = `          const safe = applySafeInvariantRepairsHost(repair, gate, { allowEdgeDrops: true }).repairs\n          if (safe.length > 0) gate = validateGraphInvariantsHost(repair, task.text, {\n            includeQuality: false,\n            extraNodes: knownNodes,\n            normalizationWarnings: repair.warnings,\n            ignoreSafeNormalizationDrops: true,\n          })\n          if (gate.blockingIssues.length > 0) {\n            // Coverage is a bounded additive recovery transaction. A bad new\n            // candidate must not authorize a rewrite, but one isolated\n            // semantic-strength drift should not veto unrelated valid recovery\n            // candidates either. Drop only drifted coverage nodes and all\n            // incident coverage edges, then re-run the complete invariant gate.\n            const pruned = pruneCoverageSemanticStrengthDriftHost(repair, gate)\n            if (pruned.length > 0) {\n              gate = validateGraphInvariantsHost(repair, task.text, {\n                includeQuality: false,\n                extraNodes: knownNodes,\n                normalizationWarnings: repair.warnings,\n                ...(safe.length > 0 ? { ignoreSafeNormalizationDrops: true } : {}),\n              })\n            }\n          }\n          if (gate.blockingIssues.length > 0) throw new Error(formatInvariantFeedbackHost(gate.blockingIssues))\n`
if (!host.includes(gateOld)) throw new Error('coverage gate block not found')
host = host.replace(gateOld, gateNew)
writeFileSync(hostPath, host)

const smokePath = 'scripts/kg-mechanism-coverage-smoke.mjs'
let smoke = readFileSync(smokePath, 'utf8')

const extractMarker = `    if (title === 'plain-fact') {\n      return { summary: '直接事实', nodes: [{ id: 'f1', type: 'fact', text: '项目包含三个文件', quote: '项目包含三个文件。', paragraph: 0 }], edges: [] }\n    }\n`
const extractReplacement = `    if (title === 'coverage-partial-prune') {\n      return {\n        summary: '预测支撑日常行动',\n        nodes: [{ id: 'n1', type: 'claim', text: '预测能力支撑着人的行动', quote: '预测能力支撑着人的行动。', paragraph: 0 }],\n        edges: [],\n      }\n    }\n    if (title === 'plain-fact') {\n      return { summary: '直接事实', nodes: [{ id: 'f1', type: 'fact', text: '项目包含三个文件', quote: '项目包含三个文件。', paragraph: 0 }], edges: [] }\n    }\n`
if (!smoke.includes(extractMarker)) throw new Error('mechanism smoke extract marker not found')
smoke = smoke.replace(extractMarker, extractReplacement)

const reviewMarker = `  async reviewCoverage(args) {\n    coverageCalls.push(args)\n    assert(args.systemPrompt.includes('只补漏，不重做'), 'coverage pass is not scoped as missing-node repair')\n    assert(args.systemPrompt.includes('纯修辞、只重复已有原则的比喻优先省略'), 'example selection does not prefer mechanism-bearing examples')\n    assert(args.prompt.includes('首轮已接受节点'), 'coverage reviewer did not receive the accepted graph')\n    return {\n`
const reviewReplacement = `  async reviewCoverage(args) {\n    coverageCalls.push(args)\n    assert(args.systemPrompt.includes('只补漏，不重做'), 'coverage pass is not scoped as missing-node repair')\n    assert(args.systemPrompt.includes('纯修辞、只重复已有原则的比喻优先省略'), 'example selection does not prefer mechanism-bearing examples')\n    assert(args.prompt.includes('首轮已接受节点'), 'coverage reviewer did not receive the accepted graph')\n    if (args.title === 'coverage-partial-prune') {\n      return {\n        nodes: [\n          { id: 'm1', type: 'example', text: '不经意的翻页动作基于大脑预测翻页后会看到后续内容而采取', quote: '哪怕是不经意的翻页动作，也是基于大脑预测翻页后会看到后续内容而采取的行动。', paragraph: 1 },\n          { id: 'm2', type: 'claim', text: '这个现象说明预测能力持续参与日常行动', quote: '这个现象可能说明预测能力持续参与日常行动。', paragraph: 2 },\n        ],\n        edges: [\n          { fromNodeId: 'm1', toNodeId: 'n1', relation: 'example', evidence: [{ paragraph: 1, quote: '哪怕是不经意的翻页动作，也是基于大脑预测翻页后会看到后续内容而采取的行动。' }] },\n          { fromNodeId: 'm2', toNodeId: 'n1', relation: 'supports', evidence: [{ paragraph: 2, quote: '这个现象可能说明预测能力持续参与日常行动。' }] },\n        ],\n      }\n    }\n    return {\n`
if (!smoke.includes(reviewMarker)) throw new Error('mechanism smoke review marker not found')
smoke = smoke.replace(reviewMarker, reviewReplacement)

const beforePlainMarker = `const beforePlain = coverageCalls.length\n`
const partialTest = `const partialText = [\n  '预测能力支撑着人的行动。',\n  '哪怕是不经意的翻页动作，也是基于大脑预测翻页后会看到后续内容而采取的行动。',\n  '这个现象可能说明预测能力持续参与日常行动。',\n].join('\\n\\n')\nconst partialStart = await handlers.get('extract')({ title: 'coverage-partial-prune', text: partialText })\nconst partial = await waitTask(partialStart.taskId)\nassert(partial.status === 'succeeded', 'coverage partial-prune extraction failed: ' + JSON.stringify(partial))\nassert(partial.result.nodes.some((node) => node.id === 'm1'), 'valid coverage candidate was lost with the drifted sibling')\nassert(!partial.result.nodes.some((node) => node.id === 'm2'), 'semantic-strength-drift coverage node was admitted')\nassert(partial.result.edges.some((edge) => edge.fromNodeId === 'm1' && edge.toNodeId === 'n1' && edge.relation === 'example'), 'valid coverage edge was lost after pruning')\nassert(!partial.result.edges.some((edge) => edge.fromNodeId === 'm2' || edge.toNodeId === 'm2'), 'incident edge of drifted coverage node survived pruning')\nassert((partial.result.warnings || []).some((warning) => String(warning).includes('coverage_pruned:node_semantic_strength_drift:m2')), 'coverage pruning was not auditable in warnings')\nassert(!(partial.result.warnings || []).some((warning) => String(warning).includes('coverage_review_failed')), 'one prunable drift incorrectly failed the whole coverage review')\nconst partialCoverage = partial.result.generation && partial.result.generation.coverage\nassert(partialCoverage && partialCoverage.attemptedBatches === 1 && partialCoverage.repairedBatches === 1 && partialCoverage.addedNodes === 1 && partialCoverage.addedEdges === 1, 'partial-prune coverage metadata is incorrect: ' + JSON.stringify(partialCoverage))\n\nconst beforePlain = coverageCalls.length\n`
if (!smoke.includes(beforePlainMarker)) throw new Error('mechanism smoke plain marker not found')
smoke = smoke.replace(beforePlainMarker, partialTest)

smoke = smoke.replace(
  `console.log(JSON.stringify({ ok: true, recoveredNodes: coverage.addedNodes, boundedReview: true, plainSkipped: true }))`,
  `console.log(JSON.stringify({ ok: true, recoveredNodes: coverage.addedNodes, boundedReview: true, partialPrune: true, plainSkipped: true }))`,
)
writeFileSync(smokePath, smoke)
