import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// Build extension/viewer.js + extension/viewer.css from src/index.client.js:
// a plain-script graph engine (no Cordis, no module system) for the Chrome
// extension popup. It slices the self-contained region between the React
// helpers and the end of GraphViewer, then exports the pieces the popup uses.
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const src = readFileSync(join(ROOT, 'src/index.client.js'), 'utf8')
const lines = src.split('\n')

const startIdx = lines.findIndex((l) => l.includes('const h = React.createElement'))
const endIdx = lines.findIndex((l) => l.includes('// --------------------------- window floor'))
if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx) throw new Error('viewer slice bounds not found')

const body = lines.slice(startIdx, endIdx).join('\n')

const bundle = `/**
 * dsh-knowledge-graph — viewer bundle for the Chrome extension popup.
 *
 * Generated by scripts/build-viewer.mjs from src/index.client.js (do not edit
 * by hand): the self-contained graph engine — node sizing, all four layouts
 * (force / circular / radial / layered), orthogonal routing, two-way
 * anchoring (makeView/splitParagraphs), and the GraphViewer React component.
 * Depends only on window.React; the popup passes a tiny ctx shim
 * ({ timeout }) in place of the Cordis context.
 */
(function () {
  'use strict'
  const React = window.React
${body}
  window.KGViewer = {
    GraphViewer,
    makeView,
    splitParagraphs,
    resolveAnchor,
    resolveNeedle,
    normalizeFor,
    tokenize,
    TYPE_META,
    TYPE_ORDER,
    REL_LABEL,
    LAYOUT_MODES,
    LAYER_Y_GAP,
    LAYER_X_GAP,
    NL,
    clamp,
    computeNodeSizes,
    layoutGraph,
    computeBBox,
    // Verification helpers are available to the extension popup if it later
    // wants to render the verification panel / apply fixes.
    VerificationPanel,
    issueTargetsOf,
    applyPatch,
    applyAllFixable,
    auditDiffLines,
    edgeKeyOf,
    withVerification,
  }
})()
`

const outDir = join(ROOT, 'extension')
mkdirSync(outDir, { recursive: true })
writeFileSync(join(outDir, 'viewer.js'), bundle)

// ---- extension/d3/*.js: the four embedded d3 sources as real files ----
// MV3 extension pages forbid eval (new Function), so the popup loads these
// before viewer.js via <script src>; viewer.js's d3force loader detects the
// preloaded globalThis.d3 and skips the eval path. Each source string is
// "<comment>\n<UMD code>"; strip the comment line and write the UMD as-is.
const d3files = [
  ['D3_TIMER_SRC', 'd3-timer.js'],
  ['D3_DISPATCH_SRC', 'd3-dispatch.js'],
  ['D3_QUADTREE_SRC', 'd3-quadtree.js'],
  ['D3_FORCE_SRC', 'd3-force.js'],
]
const d3Dir = join(outDir, 'd3')
mkdirSync(d3Dir, { recursive: true })
for (const [name, file] of d3files) {
  const mm = src.match(new RegExp(`const ${name} = "((?:[^"\\\\]|\\\\.)*)"`))
  if (!mm) throw new Error(name + ' not found in src')
  const code = mm[1].replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\')
  const nl = code.indexOf('\n')
  const umd = nl >= 0 ? code.slice(nl + 1) : code
  writeFileSync(join(d3Dir, file), umd)
}

// ---- viewer.css: the plugin's styles.insert(...) payload ----
const m = src.match(/styles\.insert\(`([\s\S]*?)`\)/)
if (!m) throw new Error('styles block not found')
const css = m[1]
  // the workbench window is a fixed overlay; the popup wants it in-flow
  // (the rule lists several custom props before `position`, so match on
  // the distinctive `--kg-win-bg: #ffffff; position: fixed;` pair)
  .replace('--kg-win-bg: #ffffff; position: fixed;', '--kg-win-bg: #ffffff; position: relative;')
writeFileSync(join(outDir, 'viewer.css'), css)

console.log('viewer.js', bundle.split('\n').length, 'lines; viewer.css', css.split('\n').length, 'lines')
